name: Python Syntax Check and Execute

on:
  push:
    branches:
      - main  # Assurez-vous d'ajuster la branche selon votre configuration

jobs:
  syntax-check-and-execute:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ajoutez cette ligne si vous avez des dépendances

      - name: Python Syntax Check
        run: |
          if ! python -m py_compile IMC.py; then
            echo "Syntax error in Python code."
            exit 1
          fi

      - name: Execute Python Code
        run: python IMC.py
